[package]
name = "nearcast"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.15.1", features = ["legacy"] }
borsh = "1.3"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
